/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HouseholdService } from "../household.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HouseholdCreateInput } from "./HouseholdCreateInput";
import { HouseholdWhereInput } from "./HouseholdWhereInput";
import { HouseholdWhereUniqueInput } from "./HouseholdWhereUniqueInput";
import { HouseholdFindManyArgs } from "./HouseholdFindManyArgs";
import { HouseholdUpdateInput } from "./HouseholdUpdateInput";
import { Household } from "./Household";
import { HouseholdMemberFindManyArgs } from "../../householdMember/base/HouseholdMemberFindManyArgs";
import { HouseholdMember } from "../../householdMember/base/HouseholdMember";
import { HouseholdMemberWhereUniqueInput } from "../../householdMember/base/HouseholdMemberWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HouseholdControllerBase {
  constructor(
    protected readonly service: HouseholdService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Household })
  @nestAccessControl.UseRoles({
    resource: "Household",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: HouseholdCreateInput,
  })
  async create(@common.Body() data: HouseholdCreateInput): Promise<Household> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Household] })
  @ApiNestedQuery(HouseholdFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Household",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Household[]> {
    const args = plainToClass(HouseholdFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Household })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Household",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: HouseholdWhereUniqueInput
  ): Promise<Household | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Household })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Household",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: HouseholdUpdateInput,
  })
  async update(
    @common.Param() params: HouseholdWhereUniqueInput,
    @common.Body() data: HouseholdUpdateInput
  ): Promise<Household | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Household })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Household",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: HouseholdWhereUniqueInput
  ): Promise<Household | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/householdMembers")
  @ApiNestedQuery(HouseholdMemberFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "HouseholdMember",
    action: "read",
    possession: "any",
  })
  async findManyHouseholdMembers(
    @common.Req() request: Request,
    @common.Param() params: HouseholdWhereUniqueInput
  ): Promise<HouseholdMember[]> {
    const query = plainToClass(HouseholdMemberFindManyArgs, request.query);
    const results = await this.service.findHouseholdMembers(params.id, {
      ...query,
      select: {
        createdAt: true,

        household: {
          select: {
            id: true,
          },
        },

        householdRole: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/householdMembers")
  @nestAccessControl.UseRoles({
    resource: "Household",
    action: "update",
    possession: "any",
  })
  async connectHouseholdMembers(
    @common.Param() params: HouseholdWhereUniqueInput,
    @common.Body() body: HouseholdMemberWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      householdMembers: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/householdMembers")
  @nestAccessControl.UseRoles({
    resource: "Household",
    action: "update",
    possession: "any",
  })
  async updateHouseholdMembers(
    @common.Param() params: HouseholdWhereUniqueInput,
    @common.Body() body: HouseholdMemberWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      householdMembers: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/householdMembers")
  @nestAccessControl.UseRoles({
    resource: "Household",
    action: "update",
    possession: "any",
  })
  async disconnectHouseholdMembers(
    @common.Param() params: HouseholdWhereUniqueInput,
    @common.Body() body: HouseholdMemberWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      householdMembers: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
